// @ts-nocheck
 /* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  BigNumberish,
  Overrides,
} from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  MockVesterV1,
  MockVesterV1Interface,
} from "../../../contracts/mock/MockVesterV1";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_accounts",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "_amounts",
        type: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "bonusRewards",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "setBonusRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516103c83803806103c883398101604081905261002f91610185565b60005b82518110156100a95781818151811061004d5761004d610256565b602002602001015160008085848151811061006a5761006a610256565b60200260200101516001600160a01b03166001600160a01b031681526020019081526020016000208190555080806100a19061026c565b915050610032565b505050610293565b634e487b7160e01b600052604160045260246000fd5b604051601f8201601f191681016001600160401b03811182821017156100ef576100ef6100b1565b604052919050565b60006001600160401b03821115610110576101106100b1565b5060051b60200190565b600082601f83011261012b57600080fd5b8151602061014061013b836100f7565b6100c7565b82815260059290921b8401810191818101908684111561015f57600080fd5b8286015b8481101561017a5780518352918301918301610163565b509695505050505050565b6000806040838503121561019857600080fd5b82516001600160401b03808211156101af57600080fd5b818501915085601f8301126101c357600080fd5b815160206101d361013b836100f7565b82815260059290921b840181019181810190898411156101f257600080fd5b948201945b838610156102265785516001600160a01b03811681146102175760008081fd5b825294820194908201906101f7565b9188015191965090935050508082111561023f57600080fd5b5061024c8582860161011a565b9150509250929050565b634e487b7160e01b600052603260045260246000fd5b60006001820161028c57634e487b7160e01b600052601160045260246000fd5b5060010190565b610126806102a26000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c806341f22724146037578063a2545fa5146060575b600080fd5b605e604236600460aa565b6001600160a01b03909116600090815260208190526040902055565b005b607d606b36600460d1565b60006020819052908152604090205481565b60405190815260200160405180910390f35b80356001600160a01b038116811460a557600080fd5b919050565b6000806040838503121560bc57600080fd5b60c383608f565b946020939093013593505050565b60006020828403121560e257600080fd5b60e982608f565b939250505056fea26469706673582212203ec81a25fb3425a25d3a2928f05732f539e1ae7ad3e2e3dcc27a98e64a303e8c64736f6c63430008140033";

type MockVesterV1ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockVesterV1ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockVesterV1__factory extends ContractFactory {
  constructor(...args: MockVesterV1ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _accounts: PromiseOrValue<string>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<MockVesterV1> {
    return super.deploy(
      _accounts,
      _amounts,
      overrides || {}
    ) as Promise<MockVesterV1>;
  }
  override getDeployTransaction(
    _accounts: PromiseOrValue<string>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_accounts, _amounts, overrides || {});
  }
  override attach(address: string): MockVesterV1 {
    return super.attach(address) as MockVesterV1;
  }
  override connect(signer: Signer): MockVesterV1__factory {
    return super.connect(signer) as MockVesterV1__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockVesterV1Interface {
    return new utils.Interface(_abi) as MockVesterV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockVesterV1 {
    return new Contract(address, _abi, signerOrProvider) as MockVesterV1;
  }
}
