// @ts-nocheck
 /* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace MockSynapseRouter {
  export type SwapQueryStruct = {
    swapAdapter: PromiseOrValue<string>;
    tokenOut: PromiseOrValue<string>;
    minAmountOut: PromiseOrValue<BigNumberish>;
    deadline: PromiseOrValue<BigNumberish>;
    rawParams: PromiseOrValue<BytesLike>;
  };

  export type SwapQueryStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber,
    string
  ] & {
    swapAdapter: string;
    tokenOut: string;
    minAmountOut: BigNumber;
    deadline: BigNumber;
    rawParams: string;
  };
}

export interface MockSynapseRouterInterface extends utils.Interface {
  functions: {
    "bridge(address,uint256,address,uint256,(address,address,uint256,uint256,bytes),(address,address,uint256,uint256,bytes))": FunctionFragment;
    "setBridgeSlippageFactor(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "bridge" | "setBridgeSlippageFactor"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "bridge",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      MockSynapseRouter.SwapQueryStruct,
      MockSynapseRouter.SwapQueryStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setBridgeSlippageFactor",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "bridge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBridgeSlippageFactor",
    data: BytesLike
  ): Result;

  events: {};
}

export interface MockSynapseRouter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockSynapseRouterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    bridge(
      to: PromiseOrValue<string>,
      chainId: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      arg4: MockSynapseRouter.SwapQueryStruct,
      destQuery: MockSynapseRouter.SwapQueryStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setBridgeSlippageFactor(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  bridge(
    to: PromiseOrValue<string>,
    chainId: PromiseOrValue<BigNumberish>,
    token: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    arg4: MockSynapseRouter.SwapQueryStruct,
    destQuery: MockSynapseRouter.SwapQueryStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setBridgeSlippageFactor(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    bridge(
      to: PromiseOrValue<string>,
      chainId: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      arg4: MockSynapseRouter.SwapQueryStruct,
      destQuery: MockSynapseRouter.SwapQueryStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    setBridgeSlippageFactor(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    bridge(
      to: PromiseOrValue<string>,
      chainId: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      arg4: MockSynapseRouter.SwapQueryStruct,
      destQuery: MockSynapseRouter.SwapQueryStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setBridgeSlippageFactor(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bridge(
      to: PromiseOrValue<string>,
      chainId: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      arg4: MockSynapseRouter.SwapQueryStruct,
      destQuery: MockSynapseRouter.SwapQueryStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setBridgeSlippageFactor(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
